#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0xC0 (0x170 - 0xB0)
// BlueprintGeneratedClass ShallowWaterSimComponent.ShallowWaterSimComponent_C
class UShallowWaterSimComponent_C : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0xB0(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextureRenderTarget2D*                Height_RT_A;                                       // 0xB8(0x8)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTextureRenderTarget2D*                Height_RT_B;                                       // 0xC0(0x8)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTextureRenderTarget2D*                Velocity_RT_A;                                     // 0xC8(0x8)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTextureRenderTarget2D*                Velocity_RT_B;                                     // 0xD0(0x8)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTextureRenderTarget2D*                Velocity_Force_RT;                                 // 0xD8(0x8)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                        Height_Idx;                                        // 0xE0(0x4)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                        Velocity_Idx;                                      // 0xE4(0x4)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*              Advect_Height_MID;                                 // 0xE8(0x8)(Edit, BlueprintVisible, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*              Advect_Velocity_MID;                               // 0xF0(0x8)(Edit, BlueprintVisible, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*              Height_Divergence_Update_MID;                      // 0xF8(0x8)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*              Gravity_Acceleration_MID;                          // 0x100(0x8)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UMaterialInstanceDynamic*>      SimMIDS;                                           // 0x108(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FIntPoint                             SimResolution;                                     // 0x118(0x8)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                             SimWorldSize;                                      // 0x120(0x8)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                             TexelWorldSize;                                    // 0x128(0x8)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                               SimLocation;                                       // 0x130(0xC)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                        DeltaT;                                            // 0x13C(0x4)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*              Seed_Water_MID;                                    // 0x140(0x8)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTexture*                              WaterVelocityTexture;                              // 0x148(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                        Res;                                               // 0x150(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         Use_SceneCapture;                                  // 0x154(0x1)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	enum class EFluidTerrainModes                TerrainMode;                                       // 0x155(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_22ED[0x2];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	int32                                        SubSteps;                                          // 0x158(0x4)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_22EE[0x4];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	class UMaterialInterface*                    Manual_Advect_Material;                            // 0x160(0x8)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                    Manual_Advect_Velocity_Material;                   // 0x168(0x8)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

	static class UClass* StaticClass();
	static class UShallowWaterSimComponent_C* GetDefaultObj();

	void PingPongMinusVelocity(class UTextureRenderTarget2D** Read_RT, class UTextureRenderTarget2D** Write_RT, int32 Temp_int_Variable, int32 Temp_int_Variable_1, int32 CallFunc_Percent_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Percent_IntInt_ReturnValue_1, class UTextureRenderTarget2D* K2Node_Select_Default, class UTextureRenderTarget2D* K2Node_Select_Default_1);
	void PingPongMinusHeight(class UTextureRenderTarget2D** Read_RT, class UTextureRenderTarget2D** Write_RT, int32 Temp_int_Variable, int32 Temp_int_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Percent_IntInt_ReturnValue, int32 CallFunc_Percent_IntInt_ReturnValue_1, class UTextureRenderTarget2D* K2Node_Select_Default, class UTextureRenderTarget2D* K2Node_Select_Default_1);
	void Clear_RTs(float Default_Water_Depth, bool Temp_bool_Variable, const struct FLinearColor& K2Node_MakeStruct_LinearColor, const struct FLinearColor& CallFunc_MakeColor_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, const struct FLinearColor& K2Node_Select_Default);
	void Create_RTs(uint8 CallFunc_MakeLiteralByte_ReturnValue, uint8 CallFunc_MakeLiteralByte_ReturnValue_1, uint8 CallFunc_MakeLiteralByte_ReturnValue_2, uint8 CallFunc_MakeLiteralByte_ReturnValue_3, uint8 CallFunc_MakeLiteralByte_ReturnValue_4, bool CallFunc_IsValid_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_2, bool CallFunc_EqualEqual_ByteByte_ReturnValue_2, class UTextureRenderTarget2D* CallFunc_CreateRenderTarget2D_ReturnValue, bool CallFunc_IsValid_ReturnValue_3, bool CallFunc_IsValid_ReturnValue_4, bool CallFunc_EqualEqual_ByteByte_ReturnValue_3, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, bool CallFunc_EqualEqual_ByteByte_ReturnValue_4, bool CallFunc_EqualEqual_IntInt_ReturnValue_2, bool CallFunc_BooleanAND_ReturnValue, class UTextureRenderTarget2D* CallFunc_CreateRenderTarget2D_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_EqualEqual_IntInt_ReturnValue_3, bool CallFunc_BooleanAND_ReturnValue_2, bool CallFunc_EqualEqual_IntInt_ReturnValue_4, bool CallFunc_BooleanAND_ReturnValue_3, class UTextureRenderTarget2D* CallFunc_CreateRenderTarget2D_ReturnValue_2, bool CallFunc_EqualEqual_IntInt_ReturnValue_5, bool CallFunc_BooleanAND_ReturnValue_4, bool CallFunc_EqualEqual_IntInt_ReturnValue_6, bool CallFunc_BooleanAND_ReturnValue_5, class UTextureRenderTarget2D* CallFunc_CreateRenderTarget2D_ReturnValue_3, bool CallFunc_EqualEqual_IntInt_ReturnValue_7, bool CallFunc_BooleanAND_ReturnValue_6, bool CallFunc_EqualEqual_IntInt_ReturnValue_8, bool CallFunc_BooleanAND_ReturnValue_7, class UTextureRenderTarget2D* CallFunc_CreateRenderTarget2D_ReturnValue_4, bool CallFunc_EqualEqual_IntInt_ReturnValue_9, bool CallFunc_BooleanAND_ReturnValue_8, bool CallFunc_BooleanAND_ReturnValue_9);
	void Simulation_Step(class UTextureRenderTarget2D** Height_RT, int32 CallFunc_Percent_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Percent_IntInt_ReturnValue_1, int32 CallFunc_Percent_IntInt_ReturnValue_2, int32 Temp_int_Variable, int32 Temp_int_Variable_1, int32 CallFunc_Percent_IntInt_ReturnValue_3, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 CallFunc_Percent_IntInt_ReturnValue_4, int32 Temp_int_Variable_2, int32 CallFunc_Percent_IntInt_ReturnValue_5, int32 Temp_int_Variable_3, int32 Temp_int_Variable_4, class UTextureRenderTarget2D* K2Node_Select_Default, int32 CallFunc_Add_IntInt_ReturnValue_2, int32 CallFunc_Percent_IntInt_ReturnValue_6, class UTextureRenderTarget2D* K2Node_Select_Default_1, int32 CallFunc_Add_IntInt_ReturnValue_3, int32 CallFunc_Percent_IntInt_ReturnValue_7, int32 Temp_int_Variable_5, int32 Temp_int_Variable_6, int32 CallFunc_Add_IntInt_ReturnValue_4, int32 CallFunc_Percent_IntInt_ReturnValue_8, int32 Temp_int_Variable_7, class UTextureRenderTarget2D* K2Node_Select_Default_2, class UTextureRenderTarget2D* K2Node_Select_Default_3, int32 Temp_int_Variable_8, int32 CallFunc_Percent_IntInt_ReturnValue_9, class UTextureRenderTarget2D* K2Node_Select_Default_4, int32 CallFunc_Clamp_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 Temp_int_Variable_9, int32 Temp_int_Variable_10, class UTextureRenderTarget2D* K2Node_Select_Default_5, class UTextureRenderTarget2D* K2Node_Select_Default_6, int32 Temp_int_Variable_11, int32 Temp_int_Variable_12, int32 CallFunc_Add_IntInt_ReturnValue_5, class UTextureRenderTarget2D* K2Node_Select_Default_7, int32 CallFunc_Percent_IntInt_ReturnValue_10, int32 CallFunc_Add_IntInt_ReturnValue_6, int32 Temp_int_Variable_13, class UTextureRenderTarget2D* K2Node_Select_Default_8, int32 Temp_int_Variable_14, int32 CallFunc_Add_IntInt_ReturnValue_7, class UTextureRenderTarget2D* K2Node_Select_Default_9, int32 CallFunc_Percent_IntInt_ReturnValue_11, int32 Temp_int_Variable_15, class UTextureRenderTarget2D* K2Node_Select_Default_10, int32 CallFunc_Add_IntInt_ReturnValue_8, int32 Temp_int_Variable_16, class UTextureRenderTarget2D* K2Node_Select_Default_11);
	void Seed_Water(class UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue);
	void Set_Sim_MID_Params(class UTexture* Forces, class UTexture* Terrain, bool CallFunc_IsValid_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue, float CallFunc_Conv_BoolToFloat_ReturnValue);
	void Create_Sim_MIDs(bool Temp_bool_Variable, class UMaterialInterface* Temp_object_Variable, bool Temp_bool_Variable_1, enum class EFluidTerrainModes Temp_byte_Variable, class UMaterialInterface* Temp_object_Variable_1, class UMaterialInterface* Temp_object_Variable_2, class UMaterialInterface* Temp_object_Variable_3, class UMaterialInterface* Temp_object_Variable_4, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class UMaterialInterface* K2Node_Select_Default, class UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue, class UMaterialInterface* K2Node_Select_Default_1, class UMaterialInterface* K2Node_Select_Default_2, class UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_1, class UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_2, TArray<class UMaterialInstanceDynamic*>& K2Node_MakeArray_Array, class UMaterialInstanceDynamic* CallFunc_CreateDynamicMaterialInstance_ReturnValue_3);
	void Initialize_ShallowWaterSim(int32 Res, enum class EFluidTerrainModes Terrain_Mode, class UTexture* Forces, class UTexture* Terrain_Texture, float Default_Water_Depth);
	void Release_Shallow_Water_Sim_RTs();
	void ExecuteUbergraph_ShallowWaterSimComponent(int32 EntryPoint, int32 K2Node_CustomEvent_Res, enum class EFluidTerrainModes K2Node_CustomEvent_Terrain_Mode, class UTexture* K2Node_CustomEvent_Forces, class UTexture* K2Node_CustomEvent_Terrain_Texture, float K2Node_CustomEvent_Default_Water_Depth);
};

}


